GET http://localhost:8080/api/books
Accept: application/json

###
GET http://localhost:8080/api/books/31
Accept: application/json

###
POST http://localhost:8080/api/books
Accept: application/json
Content-Type: application/json

{"title": "Jungle Book 12", "text": "Once upon a time...", "author_ids": ["14", "15"]}

###
PUT http://localhost:8080/api/books/31
Accept: application/json
Content-Type: application/json

{"title": "Bad title", "text": "Text is not the same", "author_ids": ["14", "15", "16"]}

###
DELETE http://localhost:8080/api/books/31
Accept: application/json

###
GET http://localhost:8080/api/authors
Accept: application/json

###
GET http://localhost:8080/api/authors/14
Accept: application/json

###
POST http://localhost:8080/api/authors
Accept: application/json
Content-Type: application/json

{"name": "Albert Einstein"}

###
PUT http://localhost:8080/api/authors/14
Accept: application/json
Content-Type: application/json

{"name": "Luke Smith"}

###
DELETE http://localhost:8080/api/authors/13
Accept: application/json

