version: "3"

services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./code:/code
      - ./conf/nginx/:/etc/nginx/conf.d

  php:
    image: azr4m/php73-fpm-mysql
    volumes:
      - ./code:/code
      - ./conf/php/add.conf.ini:/etc/php/7.3/fpm/conf.d/add.conf.ini

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wnm
      MYSQL_PASSWORD: wnm
      MYSQL_DATABASE: wnm
    ports:
      - 8081:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
